### ISSUE TITLE
downgrade target to es5

### ISSUE THREAD

**Issue by melistik** [rocketbase-io/skeleton-key#24]
Please lower the target and also mention needed polyfills for IE11, Edge and other browsers.

**Comment by Merlin-R** [comment]
We will migrate from webpack to rollup with multiple build targets, at least one of which will be an es5 target.

**Comment by Merlin-R** [comment]
Migration to rollup was done in v0.4.5, the package now provides several build targets: es modules, commonjs, umd and iife, with commonjs, umd and iife being es5 targets. Your bundler should automatically pick the correct version
